name = "Chatham Main Line Catford Loop - Wandsworth Road to Bromley South via Catford & Herne Hill"
display_name = "Chatham Main Line Catford Loop"
description = "A simulation of the Catford Loop on the Chatham Main Line."
rly_file = "ChathamMainLine-Catford.rly"
ttb_files = [ "ChathamMainLine-Catford OffPeak.ttb", "ChathamMainLine-Catford Peak.ttb",]
ssn_files = []
doc_files = [ "readme-ChathamMainLine-Catford",]
img_files = [ "ChathamMainLine-Catford.bmp",]
graphic_files = []
country_code = "GB"
year = 2022
factual = true
difficulty = 4
author = "MissCatTrap"
contributors = []
version = "1.0.0"
release_date = "2022-02-10"
